# -*- coding: utf-8 -*-
"""Titanic Survival Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UtvnukowASx12lCxOLY9qhFIY3ar9bR
"""

import kagglehub
path = kagglehub.dataset_download("zain280/titanic-data-set")
print("Path to dataset files:", path)

import os
print(os.listdir(path))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv(f"{path}/train.csv")
df.head()

df.info()

# Overall survival count
sns.countplot(x='Survived', data=df)
plt.title('Survival Count (0 = Died, 1 = Survived)')
plt.show()

# Survival by sex
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title('Survival by Sex')
plt.show()

# Survival by passenger class
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title('Survival by Passenger Class')
plt.show()

# Age distribution by survival
sns.histplot(data=df, x='Age', hue='Survived', kde=True, bins=30)
plt.title('Age Distribution by Survival')
plt.show()

# Correlation heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Survival rate by sex (%)
df.groupby('Sex')['Survived'].mean() * 100

# Family size = siblings/spouses + parents/children + self
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

# IsAlone flag - useful predictor
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

# Extract title from Name (Mr, Mrs, Miss, etc.)
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Group rare titles together
df['Title'] = df['Title'].replace(['Lady','Countess','Capt','Col','Don','Dr',
                                    'Major','Rev','Sir','Jonkheer','Dona'], 'Rare')
df['Title'] = df['Title'].replace(['Mlle','Ms'], 'Miss')
df['Title'] = df['Title'].replace('Mme', 'Mrs')

df[['Name','Title','FamilySize','IsAlone']].head()

df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

df.groupby('IsAlone')['Survived'].mean()

# Handle missing values BEFORE modeling
df['Age'] = df.groupby(['Pclass', 'Sex'])['Age'].transform(lambda x: x.fillna(x.median()))
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df = df.drop(columns=['Cabin'])  # or extract Deck first, like we did in Step 3

# One-hot encode categorical columns
df_model = pd.get_dummies(df, columns=['Sex', 'Embarked', 'Title'], drop_first=True)

df_model.columns.tolist()

features = df_model.drop(columns=['Survived', 'Name', 'Ticket', 'PassengerId'])
target = df_model['Survived']

features.head()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, random_state=42
)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

preds = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

importances = pd.Series(model.feature_importances_, index=features.columns)
importances = importances.sort_values(ascending=False)

plt.figure(figsize=(8,6))
importances.plot(kind='barh')
plt.title('Feature Importance')
plt.gca().invert_yaxis()
plt.show()

importances

# Step 7: Hyperparameter Tuning for Random Forest
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 4, 5, 6, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation accuracy:", grid_search.best_score_)

# Evaluate the tuned model on the validation set
best_model = grid_search.best_estimator_
tuned_preds = best_model.predict(X_test)

print("\nTuned model validation accuracy:", accuracy_score(y_test, tuned_preds))
print(classification_report(y_test, tuned_preds))

# Compare tuned feature importances
tuned_importances = pd.Series(best_model.feature_importances_, index=features.columns)
tuned_importances = tuned_importances.sort_values(ascending=False)

plt.figure(figsize=(8,6))
tuned_importances.plot(kind='barh')
plt.title('Feature Importance (Tuned Model)')
plt.gca().invert_yaxis()
plt.show()

df.to_csv('titanic_cleaned.csv', index=False)

from google.colab import files
files.download('titanic_cleaned.csv')